In [1]:
! pip install numpy

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [11]:
g=np.eye(1)
print(g)

[[1.]]


In [16]:
f=np.random.random((1,1))
print(f)

[[0.59032094]]


In [17]:
n=np.full((50),10)
print(n)
print(n.ndim)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10]
1


In [19]:
n= np.full((8,18),500)
print(n)
print(n.ndim)

[[500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]
 [500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500]]
2


In [21]:
n= np.full((4,3,7),245)
print(n)
print(n.ndim)

[[[245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]]

 [[245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]]

 [[245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]]

 [[245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]
  [245 245 245 245 245 245 245]]]
3


In [38]:
c=np.eye(5)
print(c)
print(c.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2


In [35]:
a= np.eye(10)
print(a)
print(a.ndim)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
2


In [73]:
b= np.random.random((10,8))
print(b)
print(b.ndim)

[[0.34708818 0.49096394 0.53393543 0.5311145  0.54453115 0.4506107
  0.49172151 0.50532673]
 [0.36040116 0.82568376 0.74028868 0.17071528 0.66893107 0.58481191
  0.92089181 0.82991157]
 [0.82530633 0.57418365 0.99846287 0.32066993 0.59383496 0.89008748
  0.50333323 0.94927826]
 [0.47798235 0.29740216 0.5052916  0.86808792 0.93822609 0.56247642
  0.0530657  0.06414431]
 [0.116789   0.12977191 0.10179419 0.98089825 0.36645177 0.40811759
  0.39340385 0.78066824]
 [0.44759711 0.61896624 0.56151094 0.01743184 0.11632298 0.91534946
  0.73568043 0.12202431]
 [0.19254548 0.00945485 0.99238498 0.43075667 0.74740998 0.69288977
  0.6195364  0.27389986]
 [0.57748489 0.3661808  0.4178917  0.44944167 0.43912024 0.46045118
  0.92366645 0.90684811]
 [0.73642346 0.87327412 0.97572899 0.48033276 0.85569006 0.28269908
  0.0304863  0.55625225]
 [0.89832223 0.89865816 0.8555959  0.5377467  0.01976131 0.09961419
  0.8485221  0.98347439]]
2


In [33]:
b=np.random.random((3,5,5))
print(b)
print(b.ndim)

[[[0.45146954 0.43213489 0.55783358 0.05627912 0.49462351]
  [0.35466425 0.41360255 0.41913147 0.85107237 0.87060991]
  [0.97338469 0.93024574 0.11128671 0.45482299 0.14469528]
  [0.67881005 0.24148363 0.09518026 0.18329718 0.2371487 ]
  [0.23455866 0.53490086 0.43206832 0.9471208  0.81867051]]

 [[0.54469303 0.43857075 0.17775695 0.22573017 0.14127318]
  [0.60711766 0.13441214 0.45268634 0.98535895 0.75778535]
  [0.08155116 0.78073119 0.87664149 0.28766424 0.1246891 ]
  [0.26536463 0.20320218 0.4209506  0.48881207 0.48949204]
  [0.05018113 0.84067358 0.93320792 0.37366138 0.79021653]]

 [[0.43409323 0.41052268 0.71373444 0.4501116  0.97935066]
  [0.63999276 0.53886159 0.66398739 0.91349126 0.50048889]
  [0.72866475 0.89511359 0.08975885 0.80525564 0.98130805]
  [0.06269145 0.88614474 0.03014296 0.19625132 0.51133233]
  [0.18183383 0.55618966 0.38614237 0.38106588 0.99529029]]]
3


In [54]:
arr= np.array([[3,4,5,7,8,9],
               [6,5,3,2,9,7],
               [4,7,6,9,2,4],
               [0,1,4,6,8,3],
               [8,2,3,5,1,9],
               [6,1,4,3,9,2]])
print(arr.shape)
print(arr.ndim)

(6, 6)
2


In [59]:
arr= np.array([[26,56,67],
               [56,23,67],
               [23,12,36],
               [76,34,68]])
print(arr.size)

12


In [55]:
arr=np.array([[[7,4,8,3,7],
               [4,2,8,7,3]],
               
               [[3,5,8,9,2],
               [7,1,3,9,5]],

               [[2,6,9,5,9],
               [2,6,3,4,1]],

               [[1,4,9,8,4],
               [0,1,4,7,3]],

               [[3,7,8,3,2],
               [7,2,1,8,2]]])

print(arr.size)
print(arr.ndim)

              
             

50
3


In [58]:
arr=np.array([[10,20,30,40,50,60],
              [50,20,80,50,80,20],
              [20,10,90,50,30,40],
              [10,30,40,70,50,50]])
len(arr)
              

4

In [57]:
arr=np.array([[[38,67,89,2,34,90,57],
               [74,23,67,4,38,67,82]],

              [[83,23,68,5,76,72,97],
               [54,87,45,4,64,85,95]],
              
              [[63,16,23,1,21,51,37],
               [65,32,17,3,38,94,36]]])
len(arr)
               
              

3

In [72]:
d= np.arange(10,200,5)
print(d)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


In [68]:
h= np.arange(50,500,10)
print(h)

[ 50  60  70  80  90 100 110 120 130 140 150 160 170 180 190 200 210 220
 230 240 250 260 270 280 290 300 310 320 330 340 350 360 370 380 390 400
 410 420 430 440 450 460 470 480 490]


In [65]:
d= np.linspace(0,20,8)
print(d)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [69]:
g= np.linspace(20,100,40)
print(g)

[ 20.          22.05128205  24.1025641   26.15384615  28.20512821
  30.25641026  32.30769231  34.35897436  36.41025641  38.46153846
  40.51282051  42.56410256  44.61538462  46.66666667  48.71794872
  50.76923077  52.82051282  54.87179487  56.92307692  58.97435897
  61.02564103  63.07692308  65.12820513  67.17948718  69.23076923
  71.28205128  73.33333333  75.38461538  77.43589744  79.48717949
  81.53846154  83.58974359  85.64102564  87.69230769  89.74358974
  91.79487179  93.84615385  95.8974359   97.94871795 100.        ]
